name: CI/CD_main

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: üêò gradlew Ïã§Ìñâ Í∂åÌïú Î∂ÄÏó¨
        run: chmod +x ./gradlew

        ## create application-database.yml
      - name: make application-database.yml
        run: |

          cd ./src/main/resources
          
          # application-database.yml ÌååÏùº ÏÉùÏÑ±
          touch ./application-database.yml
          
          # GitHub-Actions ÏóêÏÑú ÏÑ§Ï†ïÌïú Í∞íÏùÑ application-database.yml ÌååÏùºÏóê Ïì∞Í∏∞
          echo "${{ secrets.DATABASE }}" >> ./application-database.yml
        shell: bash

      - name: Generate application.properties
        run: |
          echo "commit.hash=${{ steps.slug.outputs.sha7 }}" >> ./src/main/resources/application-prod.properties
          echo "spring.datasource.url=jdbc:mysql://${{ secrets.DATASOURCE_DB_URL }}:3306/withu?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul" >> ./src/main/resources/application-prod.properties
          echo "spring.datasource.username=${{ secrets.DATASOURCE_DB_USERNAME }}" >> ./src/main/resources/application-prod.properties
          echo "spring.datasource.password=${{ secrets.DATASOURCE_DB_PASSWORD }}" >> ./src/main/resources/application-prod.properties

      - name: Run Spotless Apply
        run: ./gradlew spotlessApply

      - name: Build with Gradle
        run: |
          chmod +x gradlew 
          ./gradlew build
          
#          ./gradlew bootJar
      ## Ïõπ Ïù¥ÎØ∏ÏßÄ ÎπåÎìú Î∞è ÎèÑÏª§ÌóàÎ∏åÏóê push
      - name: web docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }} . 
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
      ## docker compose up
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            sudo docker rm $(sudo docker ps -a)
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
            cd ~
            docker-compose up -d
            sudo docker image prune -f
